version: '2'
services:
  db:
    image: mariadb:10.1
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: catch
      MYSQL_USER: catch
      MYSQL_PASSWORD: catch
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ".:/app"
      - "./.data/app:/app/web-app/uploads"
      - ".data/cache:/root/.grails/ivy-cache"
    command: ["grails", "run-app"]
    ports:
      - "8080:8080"

